### ISSUE TITLE
Login Popup-Defeat feature not working 10.13.5

### ISSUE THREAD

**Issue by gsmc-alx** [ninxsoft/MacUserGenerator#5]
Privacy, iCloud and Siri dialogs show on first login to created account under 10.13.5, unfortunately.

**Comment by jeffest-jeff** [comment]
I noticed this as well. 
This was when I installed it with a fully configured 10.13.5 system.

My goal is to try and get this to work with Netinstall, I have yet to see if this is the result with that as well.

EDIT: I got the custom Netinstall (running 10.13.0 at the moment due to SIU issues) to run this and create the local admin account. Still had to go thru the first setup options.

**Comment by joel931767** [comment]
+1 @ 10.13.6

**Comment by joel931767** [comment]
I found out why.

the HomeFolder is only created as with setPermissions() which is the last function. Which means all of the Skip functions have no place to write their changes. 

Paste the mkdir -p line from setPermissions() to setUser() and also the additional local lines and it works.

**Comment by ninxsoft** [comment]
This is now fixed: https://github.com/ninxsoft/MacUserGenerator/commit/432037cb3a7278f4689ae85d07f7b2569fce87bd

- Home folders are now fully created when run on booted volumes
- `~/Library/Preferences/` is created when run on targeted volumes
  - All remaining folders should populate dynamically upon first login

Tested on macOS High Sierra **10.13.6** and macOS Mojave **10.14.5**
